version: "3.7"
services:
  lesh_infobot:
    build:
      context: .
    command: /bin/bash -c " python fill_db.py $TABLES_PATH $DB_PATH 
      && python bot.py"
    volumes:
      - "./:/usr/local/src/:ro"
    env_file:
      - "local.env"
    network_mode: host
